---
lastfm_userbar_container_name: lastfm-userbar
lastfm_userbar_image: lastfm-userbar
lastfm_userbar_port: 8100
lastfm_userbar_app_dir: /opt/lastfm-userbar/app

docker_volumes_directory: /opt/docker
nginx_confd_path: "{{ docker_volumes_directory }}/nginx/conf.d"
nginx_custom_upstream_path: "{{ nginx_confd_path }}/custom-upstream"
nginx_docker_container_name: nginx-server
...
